RestaurantWepApp/Controllers/CategoryController.cs
using Business.Abstracts;
using Business.Constants;
using Business.Dtos.Requests;
using Business.Dtos.Responses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace RestaurantWepApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;
        private IUserService _userService;

        public CategoryController(ICategoryService categoryService, IUserService userService)
        {
            _categoryService = categoryService;
            _userService = userService;
        }

        // GET: /Category/Index
       
        public IActionResult Index()
        {
            var categories = _categoryService.GetList();
            return View(categories.Data);
        }

        // GET: /Category/Add
        public IActionResult Add()
        {
            return View("Add", new CategoryCreateDto());
        }

        // POST: /Category/Add
        [HttpPost]
        public IActionResult Add(CategoryCreateDto categoryCreateDto)
        {
            if (!ModelState.IsValid)
            {
                SetErrorMessage(Messages.FormIncomplete);
                return View("Add", categoryCreateDto);

            }
            var result = _categoryService.Add(categoryCreateDto);
            if (result.Success)
            {
                SetSuccessMessage(result.Message);
                return RedirectToAction("Index");
            }
            SetErrorMessage(result.Message);
            return View("Add", categoryCreateDto);
        }

        // GET: /Category/Edit/5
        public IActionResult Update(Guid id)
        {
            var result = _categoryService.GetById(id);
            if (result.Success)
            {
                var categoryUpdateDto = new CategoryUpdateDto
                {
                    Id = result.Data.Id,
                    Name = result.Data.Name
                };
                return View("Update", categoryUpdateDto);
            }
            return NotFound();
        }

        // POST: /Category/Edit
        [HttpPost]

        public IActionResult Update(CategoryUpdateDto categoryUpdateDto)
        {

            if (!ModelState.IsValid)
            {
                SetErrorMessage(Messages.FormIncomplete);
                return View("Update", categoryUpdateDto);
            }
            var result = _categoryService.Update(categoryUpdateDto);
            if (result.Success)
            {
                SetSuccessMessage(result.Message);
                return RedirectToAction("Index");
            }
            SetErrorMessage(result.Message);
            return View("Update", categoryUpdateDto);
        }

        // POST: /Category/Delete/5
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            var result = _categoryService.Delete(id);
            if (result.Success)
            {
                SetWarningMessage(result.Message);
                return Json(new { success = true });
            }
            SetErrorMessage(result.Message);
            return Json(new { success = false});
        }

    }
}

RestaurantWepApp/Controllers/OrderController.cs
using AutoMapper;
using Business.Abstract;
using Business.Abstracts;
using Business.Constants;
using Business.Dtos.Requests;
using Business.Dtos.Responses;
using Entities.Concrete;
using Entities.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RestaurantWepApp.Controllers;

[Authorize(Roles = "Admin")]
public class OrderController : BaseController
{
    private readonly IOrderService _orderService;
    private readonly IProductService _productService;
    private readonly IBillService _billService;
    private readonly IMapper _mapper;

    
    public OrderController(IOrderService orderService, IMapper mapper, IProductService productService, IBillService billService)
    {
        _orderService = orderService;
        _mapper = mapper;
        _productService = productService;
        _billService = billService;
    }

    // GET: /Order/Index
    public IActionResult Index()
    {
        var result = _orderService.GetList();
        if (result.Success)
        {
            return View(result.Data); 
        }
        return View("Error", result.Message);
    }

    public IActionResult ListByBilId(Guid id)
    {
        var result = _orderService.GetByBillId(id);
        ViewBag.bill = _billService.GetById(id).Data;
        if (result.Success)
        {
            return View(result.Data); // Başarılı ise detayları gösterir
        }
        return NotFound(); // Sipariş bulunamazsa 404 döndürür
    }

    public IActionResult Add()
    {
        LoadViewBagData(); 
        return View(new OrderCreateDto());
    }

   
    [HttpPost]
    public IActionResult Add(OrderCreateDto orderCreateDto)
    {
        if (ModelState.IsValid)
        {
            var result = _orderService.Add(orderCreateDto);
            if (result.Success)
            {
                SetSuccessMessage(result.Message); 
                return RedirectToAction("Index"); 
            }
            SetErrorMessage(result.Message); 
        }

        LoadViewBagData(); 
        return View(orderCreateDto); 
    }

    // POST: /Order/Edit/5
    [HttpPost]
    public IActionResult Update(OrderUpdateDto orderUpdateDto)
    {
        if (!ModelState.IsValid)
        {
            SetErrorMessage(Messages.FormIncomplete);
            return Json(new { success = false, message = Messages.FormIncomplete });
        }

        var result = _orderService.Update(orderUpdateDto);
        if (result.Success)
        {
            SetSuccessMessage(result.Message); 
            return Json(new { success = true });
        }
        SetErrorMessage(result.Message); 
        return Json(new { success = false, message = result.Message }); 
    }

    // POST: /Order/Delete/5
    
    [HttpPost]
    public IActionResult Delete(Guid id)
    {
        var result = _orderService.Delete(id);
        if (result.Success)
        {
            SetWarningMessage(result.Message);
            return Json(new { success = true }); 
        }
        SetErrorMessage(result.Message);
        return Json(new { success = false, message = result.Message }); 
    }

   
    private void LoadViewBagData()
    {
        ViewBag.StatusList = Enum.GetValues(typeof(OrderStatus))
                                 .Cast<OrderStatus>()
                                 .Select(e => new { Value = (int)e, Text = e.ToString() })
                                 .ToList();

        var products = _productService.GetList();
        if (products.Success)
        {
            ViewBag.Products = products.Data; 
        }
        else
        {
            ViewBag.Products = new List<ProductResponseDto>(); 
        }

        var bills = _billService.GetAll();
        if (bills.Success)
        {
            ViewBag.Bills = bills.Data; 
        }
        else
        {
            ViewBag.Bills = new List<BillResponseDto>(); 
        }
    }
}

RestaurantWepApp/Controllers/ProductController.cs
using AutoMapper;
using Business.Abstracts;
using Business.Constants;
using Business.Dtos.Requests;
using Business.Dtos.Responses;
using Entities.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace RestaurantWepApp.Controllers;

[Authorize(Roles = "Admin")]
public class ProductController : BaseController
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    private readonly IMapper _mapper;

    public ProductController(IProductService productService, ICategoryService categoryService, IMapper mapper)
    {
        _productService = productService;
        _categoryService = categoryService;
        _mapper = mapper;
    }

  

    // GET: /Product/Index
    public IActionResult Index()
    {
        var products = _productService.GetList();
        return View(products.Data);
    }

    // GET: /Product/Add
    public IActionResult Add()
    {
        LoadViewBagData();
        return View(new ProductCreateDto());
    }

    // POST: /Product/Add
    [HttpPost]
    public IActionResult Add(ProductCreateDto productCreateDto)
    {
        if (!ModelState.IsValid)
        {
            LoadViewBagData(); 
            SetErrorMessage(Messages.FormIncomplete);
            return View(productCreateDto);
        }

        var result = _productService.Add(productCreateDto);
        if (result.Success)
        {
            SetSuccessMessage(result.Message);
            return RedirectToAction("Index");
        }

        LoadViewBagData();
        SetErrorMessage(result.Message);
        return View(productCreateDto);
    }

    // GET: /Product/Edit/5
    public IActionResult Update(Guid id)
    {
        var result = _productService.GetById(id);
        if (result.Success)
        {
            var productUpdateDto = _mapper.Map<ProductUpdateDto>(result.Data);
            LoadViewBagData();
            return View(productUpdateDto);
        }
        return NotFound();
    }

    // POST: /Product/Edit
    [HttpPost]
    public IActionResult Update(ProductUpdateDto productUpdateDto)
    {
        if (!ModelState.IsValid) 
        {
            LoadViewBagData(); 
            SetErrorMessage(Messages.FormIncomplete);
            return View(productUpdateDto);
        }

        var result = _productService.Update(productUpdateDto);
        if (result.Success)
        {
            SetSuccessMessage(result.Message);
            return RedirectToAction("Index");
        }

        LoadViewBagData();
        SetErrorMessage(result.Message);
        return View(productUpdateDto);
    }

    // POST: /Product/Delete/5
    [HttpPost]
    public IActionResult Delete(Guid id)
    {
        var result = _productService.Delete(id);
        if (result.Success)
        {
            SetWarningMessage(result.Message);
            return Json(new { success = true });
        }
        SetErrorMessage(result.Message);
        return Json(new { success = false });
    }

    // Helper method to load data for dropdowns
    private void LoadViewBagData()
    {
        ViewBag.StatusList = Enum.GetValues(typeof(ProductStatus))
                                  .Cast<ProductStatus>()
                                  .Select(e => new { Value = (int)e, Text = e.ToString() })
                                  .ToList();
        var categories = _categoryService.GetList();

        if (categories.Success)
        {
            ViewBag.Categories = _categoryService.GetList().Data;
        }
        else
        {
            ViewBag.Categories = new List<CategoryResponseDto>();
        }
       
    }
}

RestaurantWepApp/Controllers/TableController.cs
using AutoMapper;
using Business.Abstracts;
using Business.Dtos.Requests;
using Business.Dtos.Responses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace RestaurantWepApp.Controllers;

[Authorize(Roles = "Admin")]
public class TableController : BaseController
{
    private readonly ITableService _tableService;
    private readonly IMapper _mapper;

    public TableController(ITableService tableService, IMapper mapper)
    {
        _tableService = tableService;
        _mapper = mapper;
    }

  

    // GET: /Table/Index
    public IActionResult Index()
    {
        var result = _tableService.GetList();
        if (result.Success)
        {
            var tableDtos = _mapper.Map<List<TableResponseDto>>(result.Data);
            return View(tableDtos);
        }
        return View("Error", result.Message);
    }

    // GET: /Table/Details/5
    public IActionResult Details(Guid id)
    {
        var result = _tableService.GetById(id);
        if (result.Success)
        {
            var tableDto = _mapper.Map<TableResponseDto>(result.Data);
            return View(tableDto);
        }
        return NotFound();
    }

    // GET: /Table/Create
    public IActionResult Add()
    {
        return View(new TableCreateDto());
    }

    // POST: /Table/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Add(TableCreateDto tableDto)
    {
        if (ModelState.IsValid)
        {
            var result = _tableService.Add(tableDto);
            if (result.Success)
            {
                SetSuccessMessage(result.Message); 
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", result.Message);
        }
        return View(tableDto);
    }

    // GET: /Table/Edit/5
    public IActionResult Update(Guid id)
    {
        var result = _tableService.GetById(id);
        if (result.Success)
        {
            var tableDto = _mapper.Map<TableUpdateDto>(result.Data);
            return View(tableDto);
        }
        return NotFound();
    }

    // POST: /Table/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Update(TableUpdateDto tableDto)
    {
        if (ModelState.IsValid)
        {
            var result = _tableService.Update(tableDto);
            if (result.Success)
            {
                SetSuccessMessage(result.Message); 
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", result.Message);
        }
        return View(tableDto);
    }

    // POST: /Table/Delete/5
    [HttpPost]
    public IActionResult Delete(Guid id)
    {
        var result = _tableService.Delete(id);
        if (result.Success)
        {
            SetWarningMessage(result.Message);
            return Json(new { success = true });
        }
        SetErrorMessage(result.Message);
        return Json(new { success = false });
    }
}

RestaurantWepApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Panel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/admin.css" rel="stylesheet" />

    <!-- jQuery kütüphanesi -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Toastr kütüphanesi -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <!-- Toastr CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block sidebar">
                <div class="top-section bg-warning">
                    <h4 class="sidebar-heading">Yönetici Paneli</h4>
                    <div class="user-info">
                        <p>Hoşgeldiniz, @Context.User.Identity.Name</p>
                    </div>
                </div>
                <div class="nav-links">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Category")">Kategoriler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Product")">Ürünler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Order")">Siparişler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Table")">Masalar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "StoreBill")">Mağaza Hesapları</a>
                        </li>
                        <li class="nav-item mt-4">
                            <form id="logoutForm" action="/Account/Logout" method="post" style="display: inline;">
                                <button type="submit" class="btn btn-danger btn-sm">Çıkış Yap</button>
                            </form>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Main content -->
            <main role="main" class="col-md-9 ms-sm-auto col-lg-10 px-4">
                @RenderBody()
            </main>
        </div>
    </div>

    <!-- JavaScript files -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    <script>
        $(document).ready(function () {
            // Toastr settings
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "positionClass": "toast-top-right", // Position
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000", // Duration for which the message is visible
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };

            // Show success message if exists
        @if (TempData["SuccessMessage"] != null)
        {
            <text>toastr.success('@TempData["SuccessMessage"]'); </text>
        }

                // Show error message if exists
        @if (TempData["ErrorMessage"] != null)
        {
            <text>toastr.error('@TempData["ErrorMessage"]'); </text>
        }
                //Show warning message
        @if (TempData["WarningMessage"] != null)
        {
            <text>toastr.warning('@TempData["WarningMessage"]'); </text>
        }

                });
    </script>
</body>
</html>

RestaurantWepApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

    <style>
        /* Toastr custom styles */
        .toast-success {
            background-color: #28a745 !important; /* Success - Green */
            color: white !important;
        }

        .toast-error {
            background-color: #dc3545 !important; /* Error - Red */
            color: white !important;
        }

        .toast-warning {
            background-color: #ffc107 !important; /* Warning - Yellow */
            color: black !important;
        }

        .toast-info {
            background-color: #17a2b8 !important; /* Info - Blue */
            color: white !important;
        }
    </style>
</head>
<body>
    <div class="container">       
            @RenderBody()       
    </div>

    <!-- JavaScript files -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    <script>
        $(document).ready(function () {
            // Toastr settings
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "positionClass": "toast-top-right", // Position
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000", // Duration for which the message is visible
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };

            // Show success message if exists
        @if (TempData["SuccessMessage"] != null)
        {
            <text>toastr.success('@TempData["SuccessMessage"]'); </text>
        }

                // Show error message if exists
        @if (TempData["ErrorMessage"] != null)
        {
            <text>toastr.error('@TempData["ErrorMessage"]'); </text>
        }

                // Show warning message if exists
        @if (TempData["WarningMessage"] != null)
        {
            <text>toastr.warning('@TempData["WarningMessage"]'); </text>
        }
                });
    </script>
</body>
</html>